pih-exercises/chapter6
EindhovenHaskellMeetup/meetup pull request #3
Opened 2017-05-10 11:46 UTC by rianwouters

2017-05-10 12:17 UTC, dnadales requested changes
Thanks again for the contribution. I added the tests for this Chapter 6 a week ago 😁 I invited you to the gitter channel so that we can stay up to date regarding our efforts.

I added QuickCheck tests. We can incorporate yours as well but you need to rename the functions. You could also check that your solutions also pass the tests I wrote ;)

2017-05-10 12:17 UTC, capitanbatata commented on courses/programming-in-haskell/pih-exercises/src/Chapter06.hs
> +module Chapter06 (and', concat', replicate', (!!!), elem', merge, msort) where
In the solutions branch you can see how to avoid name clashes with the prelude functions by using the `import ... hiding` construct ;)

2017-05-10 12:17 UTC, capitanbatata commented on courses/programming-in-haskell/pih-exercises/src/Chapter06.hs
> +    | n > 0 = (!!!) xs (n-1)
Remember that you can use infix notation if you think that helps readability, i.e. `xs !!! (n - 1)`.

2017-05-10 13:21 UTC, rianwouters commented on courses/programming-in-haskell/pih-exercises/src/Chapter06.hs
> +module Chapter06 (and', concat', replicate', (!!!), elem', merge, msort) where
thanks; integrated

2017-05-10 13:27 UTC, rianwouters commented on courses/programming-in-haskell/pih-exercises/src/Chapter06.hs
> +    | n > 0 = (!!!) xs (n-1)
implemented

2017-05-10 13:35 UTC, capitanbatata commented
Could you also do a pull from master, so that you have my tests as well?

2017-05-10 14:41 UTC, rianwouters commented
pulled in the latest master

2017-05-10 14:45 UTC, capitanbatata commented on courses/programming-in-haskell/pih-exercises/test/Chapter06Spec.hs
> -import           Data.List       (sort)
The QuickCheck tests seem to be gone 😱

2017-05-11 10:12 UTC, rianwouters commented
add the quicktests again

2017-05-11 10:25 UTC, merged